# NOTE: These properties are overridable via command line arguments and/or environment variables, as well as the
# default assumption that you might have your secrets in a file named "../secrets/secrets.yaml" (outside the project),
# but you can look at `config.py` to see how the configuration is loaded.

openai_api_key: "your-api-key"
openai_model: "gpt-4-turbo-2024-04-09"

# Anthropic
anth_api_key: "your-api-key"
anth_model: "claude-3-opus-20240229"

ai_service: "openai"

# For testing we use the test_project folder in this project
source_folder: "test_project"
scan_extensions: ".java, .py, .sql"
data_folder: "/home/clay/ferguson/QuantaAgent_data"
mode: "none"

# Units are in characters (bytes). This is just a safegard mainly to keep from accidentally spending too much money
max_prompt_length: 100000