# NOTE: These properties are overridable via command line arguments and/or environment variables, as well as the
# default assumption that you might have your secrets in a file named "../secrets/secrets.yaml" (outside the project),
# but you can look at `config.py` to see how the configuration is loaded.

openai_api_key: "your-api-key"
openai_model: "gpt-4o"

system_prompt: "You are a helpful assistant."

source_folder: "test_project"
scan_extensions: ".java, .sql, .py, .html, .htm, .js, .ts, .css"
data_folder: "data"

update_strategy: "whole_file" 
# update_strategy: "injection_points"

# Units are in characters (bytes). This is just a safegard mainly to keep from accidentally spending too much money
max_prompt_length: 100000